// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOMSTybgQ12gzXQiIFPf5mZ061zk_p5B8',
    appId: '1:128376529234:web:87dcab888d5fb3efb41a8b',
    messagingSenderId: '128376529234',
    projectId: 'multilingual-support-b61e8',
    authDomain: 'multilingual-support-b61e8.firebaseapp.com',
    storageBucket: 'multilingual-support-b61e8.firebasestorage.app',
    measurementId: 'G-4RJJLGWDX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAScj-75ag0cCongH_RUL3TEKkRUYKTX0o',
    appId: '1:128376529234:android:d094cccc1e307c00b41a8b',
    messagingSenderId: '128376529234',
    projectId: 'multilingual-support-b61e8',
    storageBucket: 'multilingual-support-b61e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVVCRbv9N84EvSEiJGQvKl_mu02IE6t3o',
    appId: '1:128376529234:ios:58f205e2d3e3604eb41a8b',
    messagingSenderId: '128376529234',
    projectId: 'multilingual-support-b61e8',
    storageBucket: 'multilingual-support-b61e8.firebasestorage.app',
    iosBundleId: 'com.example.multiLangApp',
  );

  static const FirebaseOptions macos = ios;
  static const FirebaseOptions windows = web;
}
